name: aws_lambda_dart_runtime
version: 1.0.3+2
description: |-
  A powerful runtime to build Lambda functions in Dart with native AWS events.
homepage: https://github.com/awslabs/aws-lambda-dart-runtime
documentation: https://awslabs.github.io/aws-lambda-dart-runtime/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_annotation: ^4.0.0

dev_dependencies:
  json_serializable: ^4.0.2
  build_runner: ^1.11.5
  test: ^1.9.4
  mockito: ^5.0.0
  pedantic: ^1.0.0
