name: aws_lambda_dart_runtime
version: 1.0.0-beta.1
author: Sebastian Doell<doels@amazon.com>
description: A Lambda Runtime Interface for Dart.
homepage: https://github.com/awslabs/aws-lambda-dart-runtime
documentation: https://awslabs.github.io/aws-lambda-dart-runtime/

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  json_annotation: ^3.0.0

dev_dependencies:
  json_serializable: ^3.2.3
  build_runner: ^1.7.2
  test: ^1.9.4
  mockito: ^4.1.1
  pedantic: ^1.0.0
